### ISSUE TITLE
為什麼不把這個寫成 userscript?

### ISSUE THREAD

**Issue by maple3142** [FlandreDaisuki/Bahamut-Daily#1]
如題 沒發佈到商店的 chrome extension 使用上很不方便
而這個插件的功能都能用 userscript 做到
cors 可以用 `GM_XmlHttpRequest` 解決

**Comment by FlandreDaisuki** [comment]
我...不太會用他那個 `GM_XmlHttpRequest`
(且 GM4 會跟其他管理器衝突，很懶得做相容)
PR welcome 😀

**Comment by maple3142** [comment]
`GM_XmlHttpRequest` 不一定要 GM 才支援吧，像是 TM 也有，VM 我沒用過

然後這個發 pr 在這邊感覺很怪

**Comment by FlandreDaisuki** [comment]
我是指 API 相容性。
GM4 的 XHR API：https://wiki.greasespot.net/GM.xmlHttpRequest
非同步，回傳 Promise
TM 的 XHR API：https://tampermonkey.net/documentation.php#GM_xmlhttpRequest
同步，使用 onXXX callback 拿到結果
- - -
其實我多一層看起來就會乾淨了
```
├── webextension
├── userscript
└── .gitignore / 其他
```

**Comment by FlandreDaisuki** [comment]
剛剛仔細看了一下... GM4 的也改回 callback 了 Orz
感覺可以寫寫看...

**Comment by FlandreDaisuki** [comment]
https://github.com/FlandreDaisuki/Bahamut-Daily/tree/userscript/userscript
雙平台的雙瀏覽器的3隻猴子，理論上打開任何巴哈網域會跳出
```
test {signin: 1或0, days: ???}
```

- [x] Windows 狐狸 T猴 🐵
- [x] Windows 狐狸 暴力猴 🐵
- [ ] ~~Windows 狐狸 油猴~~ 🙈
- [x] Windows Chrome T猴 🐵
- [ ] ~~Windows Chrome 暴力猴~~ 🙈

- [x] Linux 狐狸 T猴 🐵
- [x] Linux 狐狸 暴力猴 🐵
- [x] Linux 狐狸 油猴 🐵
- [x] Linux Chrome T猴 🐵
- [x] ~~Linux Chrome 暴力猴~~ 🙈

Chrome 的暴力猴會炸了巴哈 session，我不知道為什麼 🙈
```
登入狀態但回傳 {signin: -1}
```
Windows 油猴噴錯但什麼訊息都沒有的樣子zzz 🙈
